-- Seed data for local development only.
-- Passwords are BCrypt hashes of: Admin@123, Hr@12345, Emp@12345

INSERT INTO users (email, password_hash, role_id, active) VALUES
('admin@employeehub.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.qKzqKzqKzqKzqKzqKz', 1, TRUE),
('hr@employeehub.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.qKzqKzqKzqKzqKzqKz', 2, TRUE),
('john.doe@employeehub.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.qKzqKzqKzqKzqKzqKz', 3, TRUE),
('jane.smith@employeehub.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.qKzqKzqKzqKzqKzqKz', 3, TRUE);

-- Note: The above BCrypt hashes are placeholders. Real hashes will be generated by DataInitializer on startup.
-- This migration is kept for structure; application DataInitializer creates proper users.

INSERT INTO departments (name, code, description, active) VALUES
('Engineering', 'ENG', 'Software Engineering and Development', TRUE),
('Human Resources', 'HR', 'People Operations and Talent', TRUE),
('Finance', 'FIN', 'Finance and Accounting', TRUE),
('Sales', 'SALES', 'Sales and Business Development', TRUE),
('Marketing', 'MKT', 'Marketing and Brand', TRUE);

INSERT INTO employees (employee_code, user_id, first_name, last_name, email, phone, department_id, designation, employment_status, joining_date, salary, gender) VALUES
('EMP-001', 1, 'System', 'Admin', 'admin@employeehub.com', '+1-555-0100', 2, 'System Administrator', 'ACTIVE', '2023-01-15', 120000.00, 'OTHER'),
('EMP-002', 2, 'Sarah', 'Johnson', 'hr@employeehub.com', '+1-555-0101', 2, 'HR Manager', 'ACTIVE', '2023-02-01', 95000.00, 'FEMALE'),
('EMP-003', 3, 'John', 'Doe', 'john.doe@employeehub.com', '+1-555-0102', 1, 'Senior Software Engineer', 'ACTIVE', '2023-03-10', 110000.00, 'MALE'),
('EMP-004', 4, 'Jane', 'Smith', 'jane.smith@employeehub.com', '+1-555-0103', 1, 'Software Engineer', 'ACTIVE', '2023-04-20', 85000.00, 'FEMALE'),
('EMP-005', NULL, 'Michael', 'Brown', 'michael.brown@employeehub.com', '+1-555-0104', 3, 'Financial Analyst', 'ACTIVE', '2023-05-15', 78000.00, 'MALE'),
('EMP-006', NULL, 'Emily', 'Davis', 'emily.davis@employeehub.com', '+1-555-0105', 4, 'Sales Executive', 'ACTIVE', '2023-06-01', 72000.00, 'FEMALE'),
('EMP-007', NULL, 'David', 'Wilson', 'david.wilson@employeehub.com', '+1-555-0106', 5, 'Marketing Specialist', 'ACTIVE', '2023-07-12', 68000.00, 'MALE'),
('EMP-008', NULL, 'Lisa', 'Anderson', 'lisa.anderson@employeehub.com', '+1-555-0107', 1, 'QA Engineer', 'ACTIVE', '2023-08-05', 75000.00, 'FEMALE');

UPDATE departments SET head_id = 2 WHERE code = 'HR';
UPDATE departments SET head_id = 3 WHERE code = 'ENG';

INSERT INTO leave_balances (employee_id, leave_type, year, total_days, used_days, pending_days) VALUES
(3, 'CASUAL', 2026, 12, 2, 0),
(3, 'SICK', 2026, 10, 1, 0),
(3, 'EARNED', 2026, 15, 0, 0),
(3, 'UNPAID', 2026, 0, 0, 0),
(4, 'CASUAL', 2026, 12, 0, 0),
(4, 'SICK', 2026, 10, 0, 0),
(4, 'EARNED', 2026, 15, 0, 0),
(4, 'UNPAID', 2026, 0, 0, 0),
(5, 'CASUAL', 2026, 12, 0, 0),
(5, 'SICK', 2026, 10, 0, 0),
(5, 'EARNED', 2026, 15, 0, 0),
(5, 'UNPAID', 2026, 0, 0, 0),
(6, 'CASUAL', 2026, 12, 0, 0),
(6, 'SICK', 2026, 10, 0, 0),
(6, 'EARNED', 2026, 15, 0, 0),
(6, 'UNPAID', 2026, 0, 0, 0),
(7, 'CASUAL', 2026, 12, 0, 0),
(7, 'SICK', 2026, 10, 0, 0),
(7, 'EARNED', 2026, 15, 0, 0),
(7, 'UNPAID', 2026, 0, 0, 0),
(8, 'CASUAL', 2026, 12, 0, 0),
(8, 'SICK', 2026, 10, 0, 0),
(8, 'EARNED', 2026, 15, 0, 0),
(8, 'UNPAID', 2026, 0, 0, 0);
